on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_UNAME }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build and Push Docker Image
      run: |
        docker build -t mahalakshmi2002/githubactionspringboot .
        docker push mahalakshmi2002/githubactionspringboot
